[project]
org-name = "chanakal"
version = "0.9.5"
authors = ["Chanaka Lakmal"]
keywords = ["committer-report", "github", "pull-requests", "issues", "gmail", "email"]
repository = "https://github.com/ldclakmal/package-committer"
license = "Apache-2.0"
